image: maven:3.9.6-eclipse-temurin-17

pages:
  stage: deploy
  script:
    - mvn clean package -DskipTests
    - mkdir -p public
    # Copy the statically generated pages from the target folder
    - cp -r target/generated-static-pages/* public/
  artifacts:
    paths:
      - public
  only:
    - main
