quarkus.datasource.db-kind=mssql
quarkus.datasource.username=sa
quarkus.datasource.password=admin123!
quarkus.datasource.jdbc.url=jdbc:sqlserver://NURCHAMDANI;databaseName=DataDBENT;encrypt=true;trustServerCertificate=true
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.db-version=16.0.0
quarkus.hibernate-orm.database.version-check.enabled=false
quarkus.http.port=8080
quarkus.log.level=INFO
# Enable automatic static page generation during 'mvn package'
quarkus.qute.generate-static-pages=true
# Optional: Customize the output directory (defaults to target/generated-static-pages)
quarkus.qute.static-pages-output-dir=public
#
# application.properties
#
quarkus.log.level=DEBUG
quarkus.log.category."org.jboss.resteasy".level=DEBUG
quarkus.log.category."io.quarkus.arc".level=DEBUG
quarkus.log.category."org.jboss.resteasy.resteasy_jaxrs".level=DEBUG
quarkus.log.category."org.jboss.resteasy.resteasy_jaxrs.i18n".level=DEBUG
quarkus.arc.strict-compatibility=true
quarkus.arc.dev-mode.monitoring-enabled=true
jwt.token.duration.hours=8
jwt.secret.key=MyVerySecretKeyForJWT12345678901234567890